/* tslint:disable */
/* eslint-disable */
/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.<br>Two versions of the API are available - one that requires authentication using OpenID Connect and one that requires authentication using a X.509 client certificate.<br>The OpenAPI descriptions for the two versions are available <a href=\"https://api.aivn.kr/v3/api-docs/mcp-idreg-oidc\">here</a> and <a href=\"https://api-x509.aivn.kr/v3/api-docs/mcp-idreg-x509\">here</a>.
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowedAgentRole } from './allowed-agent-role';
 /**
 * Model object representing an agent
 *
 * @export
 * @interface Agent
 */
export interface Agent {

    /**
     * The ID of the entity in the form of a sequential integer
     *
     * @type {number}
     * @memberof Agent
     */
    id?: number;

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof Agent
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof Agent
     */
    updatedAt?: Date;

    /**
     * The id of the organization that should be given agent permissions
     *
     * @type {number}
     * @memberof Agent
     */
    idActingOrganization: number;

    /**
     * The id of the organization that is giving agent permissions
     *
     * @type {number}
     * @memberof Agent
     */
    idOnBehalfOfOrganization?: number;

    /**
     * The set of roles that this agent is allowed to have
     *
     * @type {Array<AllowedAgentRole>}
     * @memberof Agent
     */
    allowedRoles?: Array<AllowedAgentRole>;
}
