/* tslint:disable */
/* eslint-disable */
/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.<br>Two versions of the API are available - one that requires authentication using OpenID Connect and one that requires authentication using a X.509 client certificate.<br>The OpenAPI descriptions for the two versions are available <a href=\"https://api.aivn.kr/v3/api-docs/mcp-idreg-oidc\">here</a> and <a href=\"https://api-x509.aivn.kr/v3/api-docs/mcp-idreg-x509\">here</a>.
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Model object for representing a role that an agent is allowed to have
 *
 * @export
 * @interface AllowedAgentRole
 */
export interface AllowedAgentRole {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof AllowedAgentRole
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof AllowedAgentRole
     */
    updatedAt?: Date;

    /**
     * The role that you want the agent to be allowed to have
     *
     * @type {string}
     * @memberof AllowedAgentRole
     */
    roleName: AllowedAgentRoleRoleNameEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum AllowedAgentRoleRoleNameEnum {
    ORGADMIN = 'ROLE_ORG_ADMIN',
    ENTITYADMIN = 'ROLE_ENTITY_ADMIN',
    USERADMIN = 'ROLE_USER_ADMIN',
    VESSELADMIN = 'ROLE_VESSEL_ADMIN',
    SERVICEADMIN = 'ROLE_SERVICE_ADMIN',
    DEVICEADMIN = 'ROLE_DEVICE_ADMIN',
    MMSADMIN = 'ROLE_MMS_ADMIN',
    USER = 'ROLE_USER'
}

