/* tslint:disable */
/* eslint-disable */
/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.<br>Two versions of the API are available - one that requires authentication using OpenID Connect and one that requires authentication using a X.509 client certificate.<br>The OpenAPI descriptions for the two versions are available <a href=\"https://api.aivn.kr/v3/api-docs/mcp-idreg-oidc\">here</a> and <a href=\"https://api-x509.aivn.kr/v3/api-docs/mcp-idreg-x509\">here</a>.
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Agent } from './agent';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
 /**
 * 
 *
 * @export
 * @interface PageAgent
 */
export interface PageAgent {

    /**
     * @type {number}
     * @memberof PageAgent
     */
    totalPages?: number;

    /**
     * @type {number}
     * @memberof PageAgent
     */
    totalElements?: number;

    /**
     * @type {number}
     * @memberof PageAgent
     */
    size?: number;

    /**
     * @type {Array<Agent>}
     * @memberof PageAgent
     */
    content?: Array<Agent>;

    /**
     * @type {number}
     * @memberof PageAgent
     */
    number?: number;

    /**
     * @type {SortObject}
     * @memberof PageAgent
     */
    sort?: SortObject;

    /**
     * @type {boolean}
     * @memberof PageAgent
     */
    first?: boolean;

    /**
     * @type {boolean}
     * @memberof PageAgent
     */
    last?: boolean;

    /**
     * @type {PageableObject}
     * @memberof PageAgent
     */
    pageable?: PageableObject;

    /**
     * @type {number}
     * @memberof PageAgent
     */
    numberOfElements?: number;

    /**
     * @type {boolean}
     * @memberof PageAgent
     */
    empty?: boolean;
}
