/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InvoiceDto
 */
export interface InvoiceDto {

    /**
     * @type {number}
     * @memberof InvoiceDto
     */
    organizationSubscriptionId: number;

    /**
     * @type {Date}
     * @memberof InvoiceDto
     */
    invoiceDate?: Date;

    /**
     * @type {string}
     * @memberof InvoiceDto
     */
    dueDate: string;

    /**
     * @type {number}
     * @memberof InvoiceDto
     */
    amountDue: number;

    /**
     * @type {number}
     * @memberof InvoiceDto
     */
    amountPaid?: number;

    /**
     * @type {string}
     * @memberof InvoiceDto
     */
    status: string;
}
