/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Model object representing an organization
 *
 * @export
 * @interface Organization
 */
export interface Organization {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof Organization
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof Organization
     */
    updatedAt?: Date;

    /**
     * The ID of the entity in the form of a UUID
     *
     * @type {string}
     * @memberof Organization
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    phone?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    mrn: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    name: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    email: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    country?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    address?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    status: string;

    /**
     * @type {number}
     * @memberof Organization
     */
    currentBalance?: number;

    /**
     * @type {number}
     * @memberof Organization
     */
    usageCostLimit?: number;
}
