/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
import { Service } from './service';
import { ServiceUsageMetric } from './service-usage-metric';
 /**
 * 
 *
 * @export
 * @interface OrganizationServiceUsage
 */
export interface OrganizationServiceUsage {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof OrganizationServiceUsage
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof OrganizationServiceUsage
     */
    updatedAt?: Date;

    /**
     * The ID of the entity in the form of a sequential integer
     *
     * @type {number}
     * @memberof OrganizationServiceUsage
     */
    id?: number;

    /**
     * @type {Service}
     * @memberof OrganizationServiceUsage
     */
    service?: Service;

    /**
     * @type {ServiceUsageMetric}
     * @memberof OrganizationServiceUsage
     */
    usageMetric?: ServiceUsageMetric;

    /**
     * @type {Organization}
     * @memberof OrganizationServiceUsage
     */
    organization: Organization;

    /**
     * @type {number}
     * @memberof OrganizationServiceUsage
     */
    usageAmount: number;

    /**
     * @type {string}
     * @memberof OrganizationServiceUsage
     */
    usageDate: string;

    /**
     * @type {number}
     * @memberof OrganizationServiceUsage
     */
    usageCost?: number;
}
