/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SortObject } from './sort-object';
 /**
 * 
 *
 * @export
 * @interface PageableObject
 */
export interface PageableObject {

    /**
     * @type {boolean}
     * @memberof PageableObject
     */
    paged?: boolean;

    /**
     * @type {number}
     * @memberof PageableObject
     */
    pageNumber?: number;

    /**
     * @type {number}
     * @memberof PageableObject
     */
    pageSize?: number;

    /**
     * @type {number}
     * @memberof PageableObject
     */
    offset?: number;

    /**
     * @type {Array<SortObject>}
     * @memberof PageableObject
     */
    sort?: Array<SortObject>;

    /**
     * @type {boolean}
     * @memberof PageableObject
     */
    unpaged?: boolean;
}
