/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Invoice } from './invoice';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
 /**
 * 
 *
 * @export
 * @interface PageInvoice
 */
export interface PageInvoice {

    /**
     * @type {number}
     * @memberof PageInvoice
     */
    totalPages?: number;

    /**
     * @type {number}
     * @memberof PageInvoice
     */
    totalElements?: number;

    /**
     * @type {PageableObject}
     * @memberof PageInvoice
     */
    pageable?: PageableObject;

    /**
     * @type {boolean}
     * @memberof PageInvoice
     */
    first?: boolean;

    /**
     * @type {boolean}
     * @memberof PageInvoice
     */
    last?: boolean;

    /**
     * @type {number}
     * @memberof PageInvoice
     */
    size?: number;

    /**
     * @type {Array<Invoice>}
     * @memberof PageInvoice
     */
    content?: Array<Invoice>;

    /**
     * @type {number}
     * @memberof PageInvoice
     */
    number?: number;

    /**
     * @type {Array<SortObject>}
     * @memberof PageInvoice
     */
    sort?: Array<SortObject>;

    /**
     * @type {number}
     * @memberof PageInvoice
     */
    numberOfElements?: number;

    /**
     * @type {boolean}
     * @memberof PageInvoice
     */
    empty?: boolean;
}
