/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
import { Payment } from './payment';
 /**
 * Model object representing a payment method
 *
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof PaymentMethod
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof PaymentMethod
     */
    updatedAt?: Date;

    /**
     * The ID of the entity in the form of a sequential integer
     *
     * @type {number}
     * @memberof PaymentMethod
     */
    id?: number;

    /**
     * @type {Organization}
     * @memberof PaymentMethod
     */
    organization: Organization;

    /**
     * @type {string}
     * @memberof PaymentMethod
     */
    type: string;

    /**
     * @type {{ [key: string]: any; }}
     * @memberof PaymentMethod
     */
    details: { [key: string]: any; };

    /**
     * @type {boolean}
     * @memberof PaymentMethod
     */
    isDefault?: boolean;

    /**
     * @type {Array<Payment>}
     * @memberof PaymentMethod
     */
    payments?: Array<Payment>;
}
