/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ServiceUsageMetricDto
 */
export interface ServiceUsageMetricDto {

    /**
     * @type {number}
     * @memberof ServiceUsageMetricDto
     */
    serviceId: number;

    /**
     * @type {string}
     * @memberof ServiceUsageMetricDto
     */
    metricName: string;

    /**
     * @type {string}
     * @memberof ServiceUsageMetricDto
     */
    description?: string;

    /**
     * @type {string}
     * @memberof ServiceUsageMetricDto
     */
    unit: string;
}
