/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
import { OrganizationServiceUsage } from './organization-service-usage';
import { ServiceSubscription } from './service-subscription';
import { ServiceUsageMetric } from './service-usage-metric';
 /**
 * Model object representing a service
 *
 * @export
 * @interface Service
 */
export interface Service {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof Service
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof Service
     */
    updatedAt?: Date;

    /**
     * The ID of the entity in the form of a sequential integer
     *
     * @type {number}
     * @memberof Service
     */
    id?: number;

    /**
     * @type {Organization}
     * @memberof Service
     */
    organization?: Organization;

    /**
     * @type {string}
     * @memberof Service
     */
    name: string;

    /**
     * @type {string}
     * @memberof Service
     */
    description?: string;

    /**
     * @type {string}
     * @memberof Service
     */
    mmsSubject?: string;

    /**
     * @type {number}
     * @memberof Service
     */
    orgContributionWeight?: number;

    /**
     * @type {number}
     * @memberof Service
     */
    unitPrice?: number;

    /**
     * @type {boolean}
     * @memberof Service
     */
    isActive?: boolean;

    /**
     * @type {Array<OrganizationServiceUsage>}
     * @memberof Service
     */
    organizationServiceUsages?: Array<OrganizationServiceUsage>;

    /**
     * @type {Array<ServiceSubscription>}
     * @memberof Service
     */
    serviceSubscriptions?: Array<ServiceSubscription>;

    /**
     * @type {Array<ServiceUsageMetric>}
     * @memberof Service
     */
    serviceUsageMetrics?: Array<ServiceUsageMetric>;
}
