/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SortObject
 */
export interface SortObject {

    /**
     * @type {string}
     * @memberof SortObject
     */
    direction?: string;

    /**
     * @type {string}
     * @memberof SortObject
     */
    nullHandling?: string;

    /**
     * @type {boolean}
     * @memberof SortObject
     */
    ascending?: boolean;

    /**
     * @type {string}
     * @memberof SortObject
     */
    property?: string;

    /**
     * @type {boolean}
     * @memberof SortObject
     */
    ignoreCase?: boolean;
}
