/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Management Service
 * Management Service for SaaS infrastructure
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ServiceSubscription } from './service-subscription';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface UserServiceSubscription
 */
export interface UserServiceSubscription {

    /**
     * The time that the entity was created
     *
     * @type {Date}
     * @memberof UserServiceSubscription
     */
    createdAt?: Date;

    /**
     * The time that the entity was last updated
     *
     * @type {Date}
     * @memberof UserServiceSubscription
     */
    updatedAt?: Date;

    /**
     * The ID of the entity in the form of a sequential integer
     *
     * @type {number}
     * @memberof UserServiceSubscription
     */
    id?: number;

    /**
     * @type {User}
     * @memberof UserServiceSubscription
     */
    user?: User;

    /**
     * @type {ServiceSubscription}
     * @memberof UserServiceSubscription
     */
    serviceSubscription?: ServiceSubscription;

    /**
     * @type {string}
     * @memberof UserServiceSubscription
     */
    startDate: string;

    /**
     * @type {string}
     * @memberof UserServiceSubscription
     */
    endDate?: string;

    /**
     * @type {boolean}
     * @memberof UserServiceSubscription
     */
    isActive?: boolean;
}
