/* tslint:disable */
/* eslint-disable */
/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.<br>Two versions of the API are available - one that requires authentication using OpenID Connect and one that requires authentication using a X.509 client certificate.<br>The OpenAPI descriptions for the two versions are available <a href=\"https://api.aivn.kr/v3/api-docs/mcp-idreg-oidc\">here</a> and <a href=\"https://api-x509.aivn.kr/v3/api-docs/mcp-idreg-x509\">here</a>.
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Certificate } from '../models';
import { CertificateRevocation } from '../models';
import { MMS } from '../models';
import { PageMMS } from '../models';
/**
 * MmsControllerApi - axios parameter creator
 * @export
 */
export const MmsControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMMS: async (body: MMS, orgMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createMMS.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling createMMS.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMMS1: async (body: MMS, orgMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createMMS1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling createMMS1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMMS: async (orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling deleteMMS.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling deleteMMS.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMMS1: async (orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling deleteMMS1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling deleteMMS1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMMS: async (orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getMMS.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling getMMS.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMMS1: async (orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getMMS1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling getMMS1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMMSCert: async (orgMrn: string, mmsMrn: string, serialNumber: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getMMSCert.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling getMMSCert.');
            }
            // verify required parameter 'serialNumber' is not null or undefined
            if (serialNumber === null || serialNumber === undefined) {
                throw new RequiredError('serialNumber','Required parameter serialNumber was null or undefined when calling getMMSCert.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}/certificate/{serialNumber}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)))
                .replace(`{${"serialNumber"}}`, encodeURIComponent(String(serialNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMMSCert1: async (orgMrn: string, mmsMrn: string, serialNumber: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getMMSCert1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling getMMSCert1.');
            }
            // verify required parameter 'serialNumber' is not null or undefined
            if (serialNumber === null || serialNumber === undefined) {
                throw new RequiredError('serialNumber','Required parameter serialNumber was null or undefined when calling getMMSCert1.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}/certificate/{serialNumber}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)))
                .replace(`{${"serialNumber"}}`, encodeURIComponent(String(serialNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationMMSes: async (orgMrn: string, page?: number, size?: number, sort?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getOrganizationMMSes.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mmses`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationMMSes1: async (orgMrn: string, page?: number, size?: number, sort?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getOrganizationMMSes1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mmses`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        newMMSCertFromCsr: async (body: string, orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling newMMSCertFromCsr.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling newMMSCertFromCsr.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling newMMSCertFromCsr.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}/certificate/issue-new/csr`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/x-pem-file';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        newMMSCertFromCsr1: async (body: string, orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling newMMSCertFromCsr1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling newMMSCertFromCsr1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling newMMSCertFromCsr1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}/certificate/issue-new/csr`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/x-pem-file';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeMMSCert: async (body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling revokeMMSCert.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling revokeMMSCert.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling revokeMMSCert.');
            }
            // verify required parameter 'certId' is not null or undefined
            if (certId === null || certId === undefined) {
                throw new RequiredError('certId','Required parameter certId was null or undefined when calling revokeMMSCert.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}/certificate/{certId}/revoke`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)))
                .replace(`{${"certId"}}`, encodeURIComponent(String(certId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeMMSCert1: async (body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling revokeMMSCert1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling revokeMMSCert1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling revokeMMSCert1.');
            }
            // verify required parameter 'certId' is not null or undefined
            if (certId === null || certId === undefined) {
                throw new RequiredError('certId','Required parameter certId was null or undefined when calling revokeMMSCert1.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}/certificate/{certId}/revoke`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)))
                .replace(`{${"certId"}}`, encodeURIComponent(String(certId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMMS: async (body: MMS, orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateMMS.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling updateMMS.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling updateMMS.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMMS1: async (body: MMS, orgMrn: string, mmsMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateMMS1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling updateMMS1.');
            }
            // verify required parameter 'mmsMrn' is not null or undefined
            if (mmsMrn === null || mmsMrn === undefined) {
                throw new RequiredError('mmsMrn','Required parameter mmsMrn was null or undefined when calling updateMMS1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/mms/{mmsMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"mmsMrn"}}`, encodeURIComponent(String(mmsMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MmsControllerApi - functional programming interface
 * @export
 */
export const MmsControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMMS(body: MMS, orgMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).createMMS(body, orgMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMMS1(body: MMS, orgMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).createMMS1(body, orgMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).deleteMMS(orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).deleteMMS1(orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getMMS(orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getMMS1(orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMSCert(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Certificate>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getMMSCert(orgMrn, mmsMrn, serialNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMSCert1(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Certificate>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getMMSCert1(orgMrn, mmsMrn, serialNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationMMSes(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PageMMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getOrganizationMMSes(orgMrn, page, size, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationMMSes1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PageMMS>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).getOrganizationMMSes1(orgMrn, page, size, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newMMSCertFromCsr(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).newMMSCertFromCsr(body, orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newMMSCertFromCsr1(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).newMMSCertFromCsr1(body, orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeMMSCert(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).revokeMMSCert(body, orgMrn, mmsMrn, certId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeMMSCert1(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).revokeMMSCert1(body, orgMrn, mmsMrn, certId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMMS(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).updateMMS(body, orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMMS1(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await MmsControllerApiAxiosParamCreator(configuration).updateMMS1(body, orgMrn, mmsMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MmsControllerApi - factory interface
 * @export
 */
export const MmsControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMMS(body: MMS, orgMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MMS>> {
            return MmsControllerApiFp(configuration).createMMS(body, orgMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new MMS
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMMS1(body: MMS, orgMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MMS>> {
            return MmsControllerApiFp(configuration).createMMS1(body, orgMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).deleteMMS(orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).deleteMMS1(orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MMS>> {
            return MmsControllerApiFp(configuration).getMMS(orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific MMS identity
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MMS>> {
            return MmsControllerApiFp(configuration).getMMS1(orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMSCert(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Certificate>> {
            return MmsControllerApiFp(configuration).getMMSCert(orgMrn, mmsMrn, serialNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the certificate of the specified MMS with the specified serial number
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMMSCert1(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Certificate>> {
            return MmsControllerApiFp(configuration).getMMSCert1(orgMrn, mmsMrn, serialNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationMMSes(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<PageMMS>> {
            return MmsControllerApiFp(configuration).getOrganizationMMSes(orgMrn, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a page of MMS identities belonging to the given organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationMMSes1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<PageMMS>> {
            return MmsControllerApiFp(configuration).getOrganizationMMSes1(orgMrn, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newMMSCertFromCsr(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return MmsControllerApiFp(configuration).newMMSCertFromCsr(body, orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new MMS certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newMMSCertFromCsr1(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return MmsControllerApiFp(configuration).newMMSCertFromCsr1(body, orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeMMSCert(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).revokeMMSCert(body, orgMrn, mmsMrn, certId, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke the MMS certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeMMSCert1(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).revokeMMSCert1(body, orgMrn, mmsMrn, certId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMMS(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).updateMMS(body, orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing MMS identity
         * @param {MMS} body 
         * @param {string} orgMrn 
         * @param {string} mmsMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMMS1(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return MmsControllerApiFp(configuration).updateMMS1(body, orgMrn, mmsMrn, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MmsControllerApi - object-oriented interface
 * @export
 * @class MmsControllerApi
 * @extends {BaseAPI}
 */
export class MmsControllerApi extends BaseAPI {
    /**
     * Creates a new MMS
     * @param {MMS} body 
     * @param {string} orgMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async createMMS(body: MMS, orgMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MMS>> {
        return MmsControllerApiFp(this.configuration).createMMS(body, orgMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a new MMS
     * @param {MMS} body 
     * @param {string} orgMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async createMMS1(body: MMS, orgMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MMS>> {
        return MmsControllerApiFp(this.configuration).createMMS1(body, orgMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete an MMS identity
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async deleteMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).deleteMMS(orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete an MMS identity
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async deleteMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).deleteMMS1(orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a specific MMS identity
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getMMS(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MMS>> {
        return MmsControllerApiFp(this.configuration).getMMS(orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a specific MMS identity
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getMMS1(orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MMS>> {
        return MmsControllerApiFp(this.configuration).getMMS1(orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the certificate of the specified MMS with the specified serial number
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {number} serialNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getMMSCert(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Certificate>> {
        return MmsControllerApiFp(this.configuration).getMMSCert(orgMrn, mmsMrn, serialNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the certificate of the specified MMS with the specified serial number
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {number} serialNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getMMSCert1(orgMrn: string, mmsMrn: string, serialNumber: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Certificate>> {
        return MmsControllerApiFp(this.configuration).getMMSCert1(orgMrn, mmsMrn, serialNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a page of MMS identities belonging to the given organization
     * @param {string} orgMrn 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getOrganizationMMSes(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<PageMMS>> {
        return MmsControllerApiFp(this.configuration).getOrganizationMMSes(orgMrn, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a page of MMS identities belonging to the given organization
     * @param {string} orgMrn 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async getOrganizationMMSes1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<PageMMS>> {
        return MmsControllerApiFp(this.configuration).getOrganizationMMSes1(orgMrn, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new MMS certificate using CSR
     * @param {string} body A PEM encoded PKCS#10 CSR
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async newMMSCertFromCsr(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return MmsControllerApiFp(this.configuration).newMMSCertFromCsr(body, orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new MMS certificate using CSR
     * @param {string} body A PEM encoded PKCS#10 CSR
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async newMMSCertFromCsr1(body: string, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return MmsControllerApiFp(this.configuration).newMMSCertFromCsr1(body, orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Revoke the MMS certificate with the given serial number
     * @param {CertificateRevocation} body 
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {number} certId The serial number of the certificate given in decimal
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async revokeMMSCert(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).revokeMMSCert(body, orgMrn, mmsMrn, certId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Revoke the MMS certificate with the given serial number
     * @param {CertificateRevocation} body 
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {number} certId The serial number of the certificate given in decimal
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async revokeMMSCert1(body: CertificateRevocation, orgMrn: string, mmsMrn: string, certId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).revokeMMSCert1(body, orgMrn, mmsMrn, certId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update an existing MMS identity
     * @param {MMS} body 
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async updateMMS(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).updateMMS(body, orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update an existing MMS identity
     * @param {MMS} body 
     * @param {string} orgMrn 
     * @param {string} mmsMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MmsControllerApi
     */
    public async updateMMS1(body: MMS, orgMrn: string, mmsMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return MmsControllerApiFp(this.configuration).updateMMS1(body, orgMrn, mmsMrn, options).then((request) => request(this.axios, this.basePath));
    }
}
