/* tslint:disable */
/* eslint-disable */
/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.<br>Two versions of the API are available - one that requires authentication using OpenID Connect and one that requires authentication using a X.509 client certificate.<br>The OpenAPI descriptions for the two versions are available <a href=\"https://api.aivn.kr/v3/api-docs/mcp-idreg-oidc\">here</a> and <a href=\"https://api-x509.aivn.kr/v3/api-docs/mcp-idreg-x509\">here</a>.
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Certificate } from '../models';
import { CertificateRevocation } from '../models';
import { PageVessel } from '../models';
import { Service } from '../models';
import { Vessel } from '../models';
/**
 * VesselControllerApi - axios parameter creator
 * @export
 */
export const VesselControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVessel: async (body: Vessel, orgMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createVessel.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling createVessel.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVessel1: async (body: Vessel, orgMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createVessel1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling createVessel1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVessel: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling deleteVessel.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling deleteVessel.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVessel1: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling deleteVessel1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling deleteVessel1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationVessels: async (orgMrn: string, page?: number, size?: number, sort?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getOrganizationVessels.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessels`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationVessels1: async (orgMrn: string, page?: number, size?: number, sort?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getOrganizationVessels1.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessels`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVessel: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVessel.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVessel.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVessel1: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVessel1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVessel1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVesselCert: async (orgMrn: string, vesselMrn: string, serialNumber: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVesselCert.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVesselCert.');
            }
            // verify required parameter 'serialNumber' is not null or undefined
            if (serialNumber === null || serialNumber === undefined) {
                throw new RequiredError('serialNumber','Required parameter serialNumber was null or undefined when calling getVesselCert.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/{serialNumber}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)))
                .replace(`{${"serialNumber"}}`, encodeURIComponent(String(serialNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVesselCert1: async (orgMrn: string, vesselMrn: string, serialNumber: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVesselCert1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVesselCert1.');
            }
            // verify required parameter 'serialNumber' is not null or undefined
            if (serialNumber === null || serialNumber === undefined) {
                throw new RequiredError('serialNumber','Required parameter serialNumber was null or undefined when calling getVesselCert1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/{serialNumber}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)))
                .replace(`{${"serialNumber"}}`, encodeURIComponent(String(serialNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVesselServices: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVesselServices.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVesselServices.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}/services`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVesselServices1: async (orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling getVesselServices1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling getVesselServices1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}/services`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        newVesselCertFromCsr: async (body: string, orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling newVesselCertFromCsr.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling newVesselCertFromCsr.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling newVesselCertFromCsr.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/issue-new/csr`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/x-pem-file';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        newVesselCertFromCsr1: async (body: string, orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling newVesselCertFromCsr1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling newVesselCertFromCsr1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling newVesselCertFromCsr1.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/issue-new/csr`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/x-pem-file';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeVesselCert: async (body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling revokeVesselCert.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling revokeVesselCert.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling revokeVesselCert.');
            }
            // verify required parameter 'certId' is not null or undefined
            if (certId === null || certId === undefined) {
                throw new RequiredError('certId','Required parameter certId was null or undefined when calling revokeVesselCert.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/{certId}/revoke`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)))
                .replace(`{${"certId"}}`, encodeURIComponent(String(certId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeVesselCert1: async (body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling revokeVesselCert1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling revokeVesselCert1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling revokeVesselCert1.');
            }
            // verify required parameter 'certId' is not null or undefined
            if (certId === null || certId === undefined) {
                throw new RequiredError('certId','Required parameter certId was null or undefined when calling revokeVesselCert1.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}/certificate/{certId}/revoke`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)))
                .replace(`{${"certId"}}`, encodeURIComponent(String(certId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVessel: async (body: Vessel, orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateVessel.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling updateVessel.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling updateVessel.');
            }
            const localVarPath = `/oidc/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVessel1: async (body: Vessel, orgMrn: string, vesselMrn: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateVessel1.');
            }
            // verify required parameter 'orgMrn' is not null or undefined
            if (orgMrn === null || orgMrn === undefined) {
                throw new RequiredError('orgMrn','Required parameter orgMrn was null or undefined when calling updateVessel1.');
            }
            // verify required parameter 'vesselMrn' is not null or undefined
            if (vesselMrn === null || vesselMrn === undefined) {
                throw new RequiredError('vesselMrn','Required parameter vesselMrn was null or undefined when calling updateVessel1.');
            }
            const localVarPath = `/x509/api/org/{orgMrn}/vessel/{vesselMrn}`
                .replace(`{${"orgMrn"}}`, encodeURIComponent(String(orgMrn)))
                .replace(`{${"vesselMrn"}}`, encodeURIComponent(String(vesselMrn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers! = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VesselControllerApi - functional programming interface
 * @export
 */
export const VesselControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVessel(body: Vessel, orgMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Vessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).createVessel(body, orgMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVessel1(body: Vessel, orgMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Vessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).createVessel1(body, orgMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).deleteVessel(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).deleteVessel1(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationVessels(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PageVessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getOrganizationVessels(orgMrn, page, size, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationVessels1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PageVessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getOrganizationVessels1(orgMrn, page, size, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Vessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVessel(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Vessel>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVessel1(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselCert(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Certificate>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVesselCert(orgMrn, vesselMrn, serialNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselCert1(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Certificate>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVesselCert1(orgMrn, vesselMrn, serialNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselServices(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Service>>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVesselServices(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselServices1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Service>>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).getVesselServices1(orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newVesselCertFromCsr(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).newVesselCertFromCsr(body, orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newVesselCertFromCsr1(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).newVesselCertFromCsr1(body, orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeVesselCert(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).revokeVesselCert(body, orgMrn, vesselMrn, certId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeVesselCert1(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).revokeVesselCert1(body, orgMrn, vesselMrn, certId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVessel(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).updateVessel(body, orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVessel1(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await VesselControllerApiAxiosParamCreator(configuration).updateVessel1(body, orgMrn, vesselMrn, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VesselControllerApi - factory interface
 * @export
 */
export const VesselControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVessel(body: Vessel, orgMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Vessel>> {
            return VesselControllerApiFp(configuration).createVessel(body, orgMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVessel1(body: Vessel, orgMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Vessel>> {
            return VesselControllerApiFp(configuration).createVessel1(body, orgMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).deleteVessel(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).deleteVessel1(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationVessels(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<PageVessel>> {
            return VesselControllerApiFp(configuration).getOrganizationVessels(orgMrn, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a page of vessel identities of the specified organization
         * @param {string} orgMrn 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationVessels1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<PageVessel>> {
            return VesselControllerApiFp(configuration).getOrganizationVessels1(orgMrn, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Vessel>> {
            return VesselControllerApiFp(configuration).getVessel(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Vessel>> {
            return VesselControllerApiFp(configuration).getVessel1(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselCert(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Certificate>> {
            return VesselControllerApiFp(configuration).getVesselCert(orgMrn, vesselMrn, serialNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the vessel identity certificate with the given serial number
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} serialNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselCert1(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Certificate>> {
            return VesselControllerApiFp(configuration).getVesselCert1(orgMrn, vesselMrn, serialNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselServices(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Service>>> {
            return VesselControllerApiFp(configuration).getVesselServices(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the set of service identities that are linked to the specified vessel identity
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVesselServices1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Service>>> {
            return VesselControllerApiFp(configuration).getVesselServices1(orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newVesselCertFromCsr(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return VesselControllerApiFp(configuration).newVesselCertFromCsr(body, orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new vessel identity certificate using CSR
         * @param {string} body A PEM encoded PKCS#10 CSR
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async newVesselCertFromCsr1(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return VesselControllerApiFp(configuration).newVesselCertFromCsr1(body, orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeVesselCert(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).revokeVesselCert(body, orgMrn, vesselMrn, certId, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke the vessel identity certificate with the given serial number
         * @param {CertificateRevocation} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {number} certId The serial number of the certificate given in decimal
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeVesselCert1(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).revokeVesselCert1(body, orgMrn, vesselMrn, certId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVessel(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).updateVessel(body, orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
        /**
         * Update a specific vessel identity
         * @param {Vessel} body 
         * @param {string} orgMrn 
         * @param {string} vesselMrn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVessel1(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return VesselControllerApiFp(configuration).updateVessel1(body, orgMrn, vesselMrn, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VesselControllerApi - object-oriented interface
 * @export
 * @class VesselControllerApi
 * @extends {BaseAPI}
 */
export class VesselControllerApi extends BaseAPI {
    /**
     * Create a new vessel identity
     * @param {Vessel} body 
     * @param {string} orgMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async createVessel(body: Vessel, orgMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Vessel>> {
        return VesselControllerApiFp(this.configuration).createVessel(body, orgMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new vessel identity
     * @param {Vessel} body 
     * @param {string} orgMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async createVessel1(body: Vessel, orgMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Vessel>> {
        return VesselControllerApiFp(this.configuration).createVessel1(body, orgMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete a specific vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async deleteVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).deleteVessel(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete a specific vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async deleteVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).deleteVessel1(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a page of vessel identities of the specified organization
     * @param {string} orgMrn 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getOrganizationVessels(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<PageVessel>> {
        return VesselControllerApiFp(this.configuration).getOrganizationVessels(orgMrn, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a page of vessel identities of the specified organization
     * @param {string} orgMrn 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getOrganizationVessels1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<PageVessel>> {
        return VesselControllerApiFp(this.configuration).getOrganizationVessels1(orgMrn, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a specific vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVessel(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Vessel>> {
        return VesselControllerApiFp(this.configuration).getVessel(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a specific vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVessel1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Vessel>> {
        return VesselControllerApiFp(this.configuration).getVessel1(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the vessel identity certificate with the given serial number
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {number} serialNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVesselCert(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Certificate>> {
        return VesselControllerApiFp(this.configuration).getVesselCert(orgMrn, vesselMrn, serialNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the vessel identity certificate with the given serial number
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {number} serialNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVesselCert1(orgMrn: string, vesselMrn: string, serialNumber: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Certificate>> {
        return VesselControllerApiFp(this.configuration).getVesselCert1(orgMrn, vesselMrn, serialNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the set of service identities that are linked to the specified vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVesselServices(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Service>>> {
        return VesselControllerApiFp(this.configuration).getVesselServices(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the set of service identities that are linked to the specified vessel identity
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async getVesselServices1(orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Service>>> {
        return VesselControllerApiFp(this.configuration).getVesselServices1(orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new vessel identity certificate using CSR
     * @param {string} body A PEM encoded PKCS#10 CSR
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async newVesselCertFromCsr(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return VesselControllerApiFp(this.configuration).newVesselCertFromCsr(body, orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new vessel identity certificate using CSR
     * @param {string} body A PEM encoded PKCS#10 CSR
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async newVesselCertFromCsr1(body: string, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return VesselControllerApiFp(this.configuration).newVesselCertFromCsr1(body, orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Revoke the vessel identity certificate with the given serial number
     * @param {CertificateRevocation} body 
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {number} certId The serial number of the certificate given in decimal
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async revokeVesselCert(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).revokeVesselCert(body, orgMrn, vesselMrn, certId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Revoke the vessel identity certificate with the given serial number
     * @param {CertificateRevocation} body 
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {number} certId The serial number of the certificate given in decimal
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async revokeVesselCert1(body: CertificateRevocation, orgMrn: string, vesselMrn: string, certId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).revokeVesselCert1(body, orgMrn, vesselMrn, certId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update a specific vessel identity
     * @param {Vessel} body 
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async updateVessel(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).updateVessel(body, orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update a specific vessel identity
     * @param {Vessel} body 
     * @param {string} orgMrn 
     * @param {string} vesselMrn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselControllerApi
     */
    public async updateVessel1(body: Vessel, orgMrn: string, vesselMrn: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return VesselControllerApiFp(this.configuration).updateVessel1(body, orgMrn, vesselMrn, options).then((request) => request(this.axios, this.basePath));
    }
}
